#!/usr/bin/env bash

echo "=== Create Bucket ==="

if [ -z "$1" ]; then
    echo "There need to be a bucket name. Eg. ./bucket my-bucket-name"
    exit 1
fi

BUCKET_NAME=$1

# https://docs.aws.amazon.com/cli/latest/reference/s3api/create-bucket.html
aws s3api create-bucket \
    --bucket $BUCKET_NAME \
    --create-bucket-configuration="LocationConstraint=ap-south-1" \
    --query Location \
    --output text