#!/usr/bin/env bash

echo "=== List Objects ==="

if [ -z "$1" ]; then
    echo "There need to be a bucket name. Eg. ./bucket my-bucket-name"
    exit 1
fi

BUCKET_NAME=$1

aws s3api list-objects-v2 \
    --bucket $BUCKET_NAME 