#!/usr/bin/env bash

echo "=== Deploy s3 bucket via CFN ==="

STACK_NAME="cfn-s3-simple"

aws cloudformation deploy \
--template-file template.yaml \
--no-execute-changeset \
--region ap-south-1 \
--stack-name $STACK_NAME