# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3-bucket.html
AWSTemplateFormatVersion: "2010-09-09"
Description: A simple S3 BucketName
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'